blank_issues_enabled: true
contact_links:
  - name: Questions and ideas
    url: https://github.com/thepacket/optibench/discussions
    about: Discuss experiments, ask questions or propose improvements.
